#!/bin/bash
echo "what is your name"
read name
echo "enter your password"
read -s password
echo " welcome $name to Tesla"
echo "$name how can i help you today"
echo "thank you $name"
echo "it shall be done"
